adding simulating error in yaml

diff --git a/.github/workflows/demo1.yml b/.github/workflows/demo1.yml
--- a/.github/workflows/demo1.yml
+++ b/.github/workflows/demo1.yml
@@ -6,3 +6,5 @@ jobs:
     steps:
       - name: my-step
         run: echo "Hello World!"
+      - name : Simulating error
+        run: echo "Error taking place"; exit 1
